baseURL = 'https://izzawildan.my.id/'
languageCode = 'en-us'
title = 'Izza WIldan | Portofolio'
theme = 'deboge'


# Untuk Google Analytic, silahkan sesuikan
googleAnalytics = "G-1L99B7CY4K" 

[params]
    Description = "Portofolio  izza wildan ridhoni yang terdiri dari hasil projek yang sudah dikerjakan  baik "